// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnbrmgwlopirujzcgziu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuYnJtZ3dsb3BpcnVqemNneml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTI0OTcsImV4cCI6MjA2NzQyODQ5N30.47ec-BCeybGEwQAAlcyT92gaqG_ufrv1NkczpHDLRxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});